# @package _global_

# specify here default configuration
# order of defaults determines the order in which configs override each other
defaults:
  - _self_  
  - debug: null
  - model: stcnn
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: stdout  
  
  
hydra:  
  output_subdir: null  
  run:  
    dir: .
 

ckpt_path: null
saved_model: null
data_dir: /new-pool
train_file: /new-pool/ev_list/spinner/spin.h5 #/new-pool/ev_list/m3ed/car_urban_day_penno_big_loop.h5
test_file: /new-pool/ev_list/spinner/spin.h5 #/new-pool/ev_list/m3ed/car_urban_day_penno_big_loop.h5
batch_size:  64
max_epochs: 200
val_epochs: 120
lr: 1e-3
interval: 30
log_int: 40
workers: 16
comp: false
device: cuda
